apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-network-NetworkPolicy
spec:
  podSelector:
    matchLabels:
      app: backend 
  policyTypes:
  - Ingress
  Ingress:
  -from:
    - podSelector:
        matchLabels:
          app: frontend